name: harbor

on:
  workflow_dispatch:
  # push:
  # branches-ignore:
  #   - main
  # branches:
    # - main

jobs:

  build:
    runs-on: ubuntu-latest
    #! env:
    #!   IMAGE_NAME: 'appstream'
    #!   TAG: 'latest'
    #!   DOCKER_DIR: '.'
    #!   CONTEXT: '.'
    #!   PIP_WHEEL_FILENAME: 'appstreamer-0.1.1-py3-none-any.whl'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: 20.x
          submodules: true
          lfs: true
          ssh-key: ${{ secrets.ACCESS_KEY }}

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make git-lfs

      - name: Update submodules
        run: |
          git submodule update --init --recursive

      - name: Set up Git LFS
        run: |
          git lfs pull
          ls -lah ./src/flask/dist
          ls -lah ./src/ui/dist

      # - name: Load config.mk file
      #   uses: falti/dotenv-action@v1.0.4
      #   with:
      #     path: config.mk
      #     keys-case: "bypass"
      #     log-variables: true
      #     export-variables: true

      - name: Extract Variables from config.mk
        id: vars
        run: |
          . ./extract-vars.sh config.mk

      - name: Show exported variables from config.mk
        run: |
          echo "Extracted vars from config.mk..."
          echo "             COMMENT: ${{ steps.vars.outputs.COMMENT}}"
          echo "   VICE_PARENT_IMAGE: ${{ steps.vars.outputs.VICE_PARENT_IMAGE }}"
          echo "     VICE_PARENT_TAG: ${{ steps.vars.outputs.VICE_PARENT_TAG }}"
          echo "           VICE_NAME: ${{ steps.vars.outputs.VICE_NAME }}"
          echo "    VICE_DKR_VERSION: ${{ steps.vars.outputs.VICE_DKR_VERSION }}"
          echo "       VICE_DKR_DIR: ${{ steps.vars.outputs.VICE_DKR_DIR }}"
          echo "           FLASK_DIR: ${{ steps.vars.outputs.FLASK_DIR}}"
          echo "            NODE_DIR: ${{ steps.vars.outputs.NODE_DIR}}"
          echo "             CONTEXT: ${{ steps.vars.outputs.CONTEXT}}"
#          echo "  PIP_WHEEL_FILENAME: ${{ steps.vars.outputs.PIP_WHEEL_FILENAME }}"

      ## Commented out (Dockerfile now installs wheel from /tmp)
      # - name: Copy whl from our submodule dist tracked in LFS
      #   id: flaskwheel
      #   run: |
      #     mkdir -p ${{ steps.vars.outputs.DOCKER_DIR }}/dist/flask/
      #     cp ${{ steps.vars.outputs.FLASK_DIR}}/dist/${{ steps.vars.outputs.PIP_WHEEL_FILENAME }} ${{ steps.vars.outputs.DOCKER_DIR }}/dist/flask/.
      #     ls -lah ${{ steps.vars.outputs.DOCKER_DIR }}/dist/flask

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.8.0
        env:
          STEP_DEBUG: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to harbor
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: harbor.cyverse.org
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_CLISECRET }}

      #! - name: Load .env.docker file
      #!   run: |
      #!     set -a
      #!     source .env.docker
      #!     export PIP_WHEEL_FILENAME
      #!     echo "PIP_WHEEL_FILENAME=$PIP_WHEEL_FILENAME"
      #!     set +a

      #! removed from below
      #!   echo "PIP_WHEEL_FILENAME=${{ env.PIP_WHEEL_FILENAME }}"
      #!   echo "APPSTREAM_LAMBDA_API=${{ env.APPSTREAM_LAMBDA_API }}"

      - name: Print environment variables
        run: |
          echo "VICE_PARENT_IMAGE=${{ steps.vars.outputs.VICE_PARENT_IMAGE }}"
          echo "VICE_PARENT_TAG=${{ steps.vars.outputs.VICE_PARENT_TAG }}"
          echo "VICE_NAME=${{ steps.vars.outputs.VICE_NAME }}"
          echo "VICE_NAME=${{ steps.vars.outputs.VICE_NAME }}"
          echo "VICE_DKR_VERSION=${{ steps.vars.outputs.VICE_DKR_VERSION }}"
          echo "VICE_DKR_DIR=${{ steps.vars.outputs.VICE_DKR_DIR }}"
        env:
          STEP_DEBUG: true

      - name: Verify files/submodules are okay
        id: verify_things_are_as_they_should_be
        env:
          VICE_DKR_DIR: ${{ steps.vars.outputs.VICE_DKR_DIR }}
        run: |
          test -d ./src/flask && test -d ./src/flask/dist && ls ./src/flask/dist
          test -d ./src/flask && test -d ./src/ui/dist && ls ./src/ui/dist
          test -d ./src/vice && test -d ./src/vice/latest && ls ./src/vice/latest

      - name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v4.1.1
        env:
          STEP_DEBUG: true
        with:
          #! context: latest
          context: ${{ steps.vars.outputs.CONTEXT }}
          #! todo: simplfy path
          file: ${{ steps.vars.outputs.VICE_DKR_DIR }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          platforms: linux/amd64,linux/arm64
          #! how can we make appstream:latest change to our environment
          tags: |
            harbor.cyverse.org/vice/appstream:latest
          build-args: |
            VICE_PARENT_IMAGE=${{ steps.vars.outputs.VICE_PARENT_IMAGE }}
            VICE_PARENT_TAG=${{ steps.vars.outputs.VICE_PARENT_TAG }}
            VICE_DKR_VERSION=${{ steps.vars.outputs.VICE_DKR_VERSION }}
            VICE_DKR_DIR=${{ steps.vars.outputs.VICE_DKR_DIR }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
